# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chabob' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chabob

  target 'ChabobTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChabobUITests' do
    # Pods for testing
  end

  pod 'NMapsMap','3.16.0'

end
